services:
  traefik:
    image: traefik:3.0.1
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "81:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"