import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import { Header } from "@/features/Header";
import { getLocale, getMessages, getTimeZone } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const timeZone = await getTimeZone()
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers messages={messages} locale={locale} timeZone={timeZone}>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
