services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_DOMAIN=${DOMAIN}

    labels:
      - "traefik.http.routers.frontend.rule=Host(`business.${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
