name: CI Build

on: [pull_request]

env:
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  DOMAIN: ${{ secrets.DOMAIN }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

  PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
  PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}

  COMPOSE_FILE: ${{ secrets.COMPOSE_FILE }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build images
        run: docker compose build
