name: CI Build

on: [pull_request]

env:
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  DOMAIN: ${{ secrets.DOMAIN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}


jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend image
        run: docker compose -f docker-compose.yml build frontend

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker compose -f docker-compose.yml build backend