name: CI Deploy

on:
  push:
    branches:
      - master

env:
  LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
  GIN_MODE: ${{ secrets.GIN_MODE }}
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  DOMAIN: ${{ secrets.DOMAIN }}
  POSTGRES_USERSERVICE_USER: ${{ secrets.POSTGRES_USERSERVICE_USER }}
  POSTGRES_USERSERVICE_PASSWORD: ${{ secrets.POSTGRES_USERSERVICE_PASSWORD }}
  POSTGRES_USERSERVICE_DB: ${{ secrets.POSTGRES_USERSERVICE_DB }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
  COMPOSE_FILE: ${{ secrets.COMPOSE_FILE }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          docker compose build
          docker compose up -d --remove-orphans