name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:

env:
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  DOMAIN: ${{ secrets.DOMAIN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker images
        run: |
          docker-compose -f ./docker-compose.yml build
          docker-compose -f ./docker-compose.yml up -d --remove-orphans