name: CI Deploy

on:
  push:
    branches:
      - master

env:
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  DOMAIN: ${{ secrets.DOMAIN }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

  PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
  PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}

  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}

  YANDEX_MAPS_API_KEY: ${{ secrets.YANDEX_MAPS_API_KEY }}

  YANDEX_CAPTCHA_KEY: ${{ secrets.YANDEX_CAPTCHA_KEY }}

  COMPOSE_FILE: ${{ secrets.COMPOSE_FILE }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          docker compose build
          docker compose up -d --remove-orphans
