name: CI Deploy

on:
  push:
    branches:
      - master

env:
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  DOMAIN: ${{ secrets.DOMAIN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
  VITE_API: ${{ secrets.VITE_API }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          docker compose -f ./docker-compose.yml build
          docker compose -f ./docker-compose.yml up -d --remove-orphans